# <i><font color = deeppink >NUMPY</font></i>

- Linear algebra library in python
- Used for performing mathematical and logical operations on Arrays
- Provides features for operations on multi-dimensional arrays and matrices in Python

In [3]:
import numpy as np
a=np.array([1,2,3]) #list
b=np.array((1,2,3))  #tuple
print(a)
print(b)

[1 2 3]
[1 2 3]


In [7]:
b[1]=4

In [5]:
b

array([1, 4, 3])

In [6]:
c=np.array([[1,2,3],[4,5,6]]) #2d array
c

array([[1, 2, 3],
       [4, 5, 6]])

### Ndarray Object
- Most important object defined in NumPy is an N-dimensional array type called ndarray
- Describes the collection of items of the same type
- Items can be accessed usng a zero-based index
- Every item in an ndarray takes the same size of block in the memory
- Each element in ndarray is an object of data-type object(called dtytpe).


In [8]:
c[0:]

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
c[:1]

array([[1, 2, 3]])

In [10]:
a[0]

1

In [11]:
a[1:2]

array([2])

In [12]:
a[1:3]

array([2, 3])

In [13]:
a[1:]

array([2, 3])

### Intializating Numpy Array

### intailise an array of 'x' X 'y' dimension with 0


In [23]:
import numpy as np
#np.zeros(rows,columns)
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### arranging numbers between x and y with an interval of z


In [32]:
import numpy as np
#np.arrange(startnum,endnum,interval)
np.arange(10,25,5)

array([10, 15, 20])

In [33]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

### arranging 'z' numbers between x and y


In [34]:
import numpy as np
#np.linspace(startnum,endnum,numberofpoints)
np.linspace(5,10,16)

array([ 5.        ,  5.33333333,  5.66666667,  6.        ,  6.33333333,
        6.66666667,  7.        ,  7.33333333,  7.66666667,  8.        ,
        8.33333333,  8.66666667,  9.        ,  9.33333333,  9.66666667,
       10.        ])

In [31]:
np.linspace(7,10,5)

array([ 7.  ,  7.75,  8.5 ,  9.25, 10.  ])

In [28]:
np.linspace(5,6,10)

array([5.        , 5.11111111, 5.22222222, 5.33333333, 5.44444444,
       5.55555556, 5.66666667, 5.77777778, 5.88888889, 6.        ])

### filling SAME number in a array of dimension x X y

In [39]:
import  numpy as np
#np.full((rownum,colnum),numbertofill)
np.full((2,2),5)

array([[5, 5],
       [5, 5]])

In [37]:
np.full((2,4),6)

array([[6, 6, 6, 6],
       [6, 6, 6, 6]])

### filling RANDOM numbers in a array of dimension x X y 

In [40]:
import numpy as np
np.random.random((2,2))

array([[0.05966326, 0.74225232],
       [0.08007982, 0.04460421]])

## Numpy Array Inspection

### ndarray.shape
- Returns a tuple consisting of array dimensions.can also be used to resize the array

In [48]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])


In [49]:
print(a)
#np.array.shape() return tuple(rownum,colnum)
print(a.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [51]:
b = np.array([[1,2,3,4],[4,5,6,5],[9,4,7,6],[6,0,3,8],[8,4,7,2]])
print(b)
print(b.shape)


[[1 2 3 4]
 [4 5 6 5]
 [9 4 7 6]
 [6 0 3 8]
 [8 4 7 2]]
(5, 4)


In [54]:
b.shape=(4,5)
print(b.shape[0])
b

4


array([[1, 2, 3, 4, 4],
       [5, 6, 5, 9, 4],
       [7, 6, 6, 0, 3],
       [8, 8, 4, 7, 2]])

In [57]:
s=np.array([[1,2,3,4],[4,5,6,7]])
s.shape=(8,1)
s

array([[1],
       [2],
       [3],
       [4],
       [4],
       [5],
       [6],
       [7]])

In [62]:
#np.arrange(numberof points needed)
#will place the numbers between 0 till that number
a=np.arange(24)

In [63]:
a.size

24

In [64]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

### ndarray.ndim
- returns the dimension of the array

In [66]:
import numpy as np
a=np.arange(24)
print(a.ndim)
b=a.reshape(2,4,3)
print(b.ndim)

1
3


### ndarray.dtype
- returns datatype of an array

In [68]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [69]:
a.dtype

dtype('int32')

### numpy array mathematics

In [70]:
np.sum([10,20])

30

In [77]:
# axis=0 does colwise sum
np.sum([[0,1],[0,5]],axis=0)

array([0, 6])

In [78]:
# axis=1 does rowwise sum
np.sum([[0,1],[0,5]],axis=1)

array([1, 5])

In [76]:
a=np.array([5,10])
b=np.array([2,3])
print(np.sum([a,b]))
print(np.subtract(a,b))

20
[3 7]


In [79]:
print(np.divide(a,b))

[2.5        3.33333333]


In [80]:
print(np.multiply(a,b))

[10 30]


In [81]:
np.exp(a)

array([  148.4131591 , 22026.46579481])

In [82]:
np.sqrt(a)

array([2.23606798, 3.16227766])

In [83]:
np.sin(a)

array([-0.95892427, -0.54402111])

In [84]:
np.cos(a)

array([ 0.28366219, -0.83907153])

In [85]:
np.log(a)

array([1.60943791, 2.30258509])

### array comparison

#### element wise comparison


In [86]:
a=[1,2,3]
b=[4,2,3]
np.equal(a,b)

array([False,  True,  True])

#### array-wise comparison


In [90]:
a=[1,2,4]
b=[2,2,4]
c=[1,2,4]
np.array_equal(a,b)

False

### Aggregrate functions

In [91]:
np.sum(a)

7

In [92]:
np.min(a)

1

In [93]:
np.mean(a)

2.3333333333333335

In [94]:
np.median(a)

2.0

In [95]:
np.corrcoef(a)

1.0

In [96]:
np.std(a)

1.247219128924647

## numpy broadcasting

In [97]:
# numpy array gets inflated to match with dimensionsof first array

In [99]:
import numpy as np
a= np.array([[1,2,3,4],[4,5,6,5],[9,4,7,6],[6,0,3,8]])
b=np.array([0,1,2,3])
print('first array:\n',a,'\n')
print('second array:\n',b,'\n')
print('first array + second array :\n',a+b)

first array:
 [[1 2 3 4]
 [4 5 6 5]
 [9 4 7 6]
 [6 0 3 8]] 

second array:
 [0 1 2 3] 

first array + second array :
 [[ 1  3  5  7]
 [ 4  6  8  8]
 [ 9  5  9  9]
 [ 6  1  5 11]]


## Numpy indexing and slicing

### Index refers to a position

### slicing takes the element from given index to another given index
- [start:end]

In [108]:
a= np.array([[1,2,3,],[4,5,6,],[9,4,7]])
print(a[0]) # returns 1st element
print(a[:1,])# returns 1st row
print(a[1,2])# returns element of 1st row&2nd col
print(a[:2,1:]) #extracting till row=1(0,1),col index starting from 1 till last

[1 2 3]
[[1 2 3]]
6
[[2 3]
 [5 6]]


- numpy consumes less memory,faster,more convenient than list